spring:
  application:
    name: CLOUD-NATIVE
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml

  datasource:
    druid:
      db-type: com.alibaba.druid.pool.DruidDataSource
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://127.0.0.1:5432/ivory
      username: postgres
      password: "highgo@123"
  jpa:
    show-sql: false
    open-in-view: false
    properties:
      javax.persistence.validation.mode: none
#      hibernate:
#        temp:
#          use_jdbc_metadata_defaults: false

  jackson:
    date-format: "yyyy-MM-dd HH:mm:ss"
    time-zone: GMT
    serialization:
      write-dates-as-timestamps: false
common:
  version: v1
  request-path-prefix: /cloudapi/api
  alert-path-prefix: alert
  serviceName: ivory
  namespace: ivory
#  storageClassLabels: "{'cnp.inspurcloud.cn/system-storageclass': 'false'}"
  refreshWatcherTaskTime: 600000 # 单位ms 默认10分钟
  linuxk8sConfigPath: /root/.kube/config
#  ivoryPgKernelVersion: 15 #数据库内核版本
#  ivoryVersion: 2.3 #ivory版本
  ivoryPgKernelVersion: 16 #数据库内核版本
  ivoryVersion: 3.0 #ivory版本
logging:
  level:
#    com:
#      inspur:
#        common: ERROR
    org:
      hibernate: error
    root: info
#  config: config/spring_pro_logback.xml

images:
#  image:
#    db: harbor.highgo.com/highgo/crunchy-highgo:sm3nodemx
#    backrest: harbor.highgo.com/highgo/crunchy-pgbackrest:sm3-v2
#    pgadmin: harbor.highgo.com/highgo/crunchy-pgadmin4:hgadmin2
#    exporter: harbor.highgo.com/highgo/crunchy-postgres-exporter:v1.5
#  image:
#    db: docker.io/ivorysql/ivorysql:ubi8-2.2-1.1-1
#    backrest: docker.io/ivorysql/pgbackrest:ubi8-2.45-1.1-1
#    pgadmin: docker.io/ivorysql/pgadmin:ubi8-7.4-1.1-1
#    exporter: docker.io/ivorysql/postgres-exporter:ubi8-0.13.2-1.1-1
  image:
    db: docker.io/ivorysql/ivorysql:ubi8-3.0-2.0-1
    backrest: docker.io/ivorysql/pgbackrest:ubi8-2.47-2.0-1
    pgadmin: docker.io/ivorysql/pgadmin:ubi8-8.0-2.0-1
    exporter: docker.io/ivorysql/postgres-exporter:ubi8-0.15.0-2.0-1
server:
  port: 8081
  error:
    include-exception: true
    include-message: always

cluster:
    user: pguser
#    user: hguser
    group: ivory-operator.ivorysql.org
#    group: highgo-operator.inspur.com
    version: v1beta1
#    version: v1beta1
    kind: IvoryCluster
#    kind: PostgresCluster
    plural: ivoryclusters
#    plural: highgoclusters
    singular: ivorycluster
#    singular: highgocluster
    instanceIdName: ivory/instanceId
#    instanceIdName: highgo/instanceId
    clusterId: ivory/clusterId
#    clusterId: highgo/clusterId
#    prometheusFilter: highgo/user
    prometheusFilter: ivory/user
    clusterNameLabel: ${cluster.group}/cluster
    clusterRoleLabel: ${cluster.group}/role
    clusterDataLabel: ${cluster.group}/data
    crBackupAnnotation: ${cluster.group}/pgbackrest-backup
    crRestoreAnnotation: ${cluster.group}/pgbackrest-restore
    grafanaName: grafana
#    grafanaName: crunchy-grafana
    alertManagerName: alertmanager
#    alertManagerName: crunchy-alertmanager
    prometheusName: prometheus
#    prometheusName: crunchy-prometheus
