apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    vendor: ivory
  name: prometheus-sa

---

apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    vendor: ivory
  name: alertmanager

---

apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    vendor: ivory
  name: grafana
